pipeline:
  docker-build:
    image: docker:17.09.1
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    commands:
      - docker build -t hocs-docker-tools .
    when:
      branch: [master, refs/tags/*]
      event: [push, tag]

  install-docker-image:
    image: docker:17.09.1
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    secrets:
      - docker_password
    commands:
      - docker login -u="ukhomeofficedigital+hocs" -p=$${DOCKER_PASSWORD} quay.io
      - docker tag hocs-info-service quay.io/ukhomeofficedigital/hocs-docker-tools:build-$${DRONE_BUILD_NUMBER}
      - docker tag hocs-info-service quay.io/ukhomeofficedigital/hocs-docker-tools:latest
      - docker push quay.io/ukhomeofficedigital/hocs-docker-tools:build-$${DRONE_BUILD_NUMBER}
      - docker push quay.io/ukhomeofficedigital/hocs-docker-tools:latest      
    when:
      branch: master
      event: push